In [1]:
# Numpy Arrays

In [2]:
import numpy as np

In [3]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array_list = np.array(mylist)

In [7]:
type(array_list)

numpy.ndarray

In [8]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
my_array = np.arange(0,11,1)

In [11]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
type(my_array)

numpy.ndarray

In [13]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(2,3)

array([[0.16824885, 0.58798945, 0.51197704],
       [0.69763536, 0.42048818, 0.87147287]])

In [16]:
np.random.randn(4)

array([ 0.22214283, -0.2417544 ,  1.49807745,  0.51256771])

In [17]:
np.random.randint(1,11, (2,3))

array([[ 2,  6,  3],
       [10,  6,  8]])

In [18]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
arr = np.arange(0,25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr = np.random.randint(0,101,10)

In [23]:
arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [24]:
arr.max()

99

In [25]:
arr.min()

2

In [26]:
arr.argmax()

5

In [27]:
arr.argmin()

7

In [28]:
arr.dtype

dtype('int32')

In [29]:
type(arr)

numpy.ndarray

In [32]:
arr.shape

(10,)

In [33]:
arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [34]:
arr.shape

(10,)

In [35]:
# Numpy Indexing and Selection

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[2:5]

array([2, 3, 4])

In [40]:
arr[:4]

array([0, 1, 2, 3])

In [41]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[0:5] = 100

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr = arr[0:5]

In [48]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr[:] = 99

In [51]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [55]:
arr_copy = arr.copy()

In [56]:
arr_copy[:] = 100

In [57]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [60]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [62]:
arr_2d[:2, 1:3]

array([[10, 15],
       [25, 30]])

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [66]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
# Numpy Operations

In [68]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [69]:
total_rolls_over_two = print(len(dice_rolls[dice_rolls>2]))

19


In [70]:
total_rolls_over_two