In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.iloc[:, :-1]

In [7]:
y = df.iloc[:, -1]

In [13]:
# Polynomial converter and features
# Train Test Split
# Feature Scaling
# Training Models

In [ ]:
# POLYNOMIAL CONVERTER AND FEATURES

In [10]:
from sklearn.preprocessing import PolynomialFeatures

In [11]:
poly_converter = PolynomialFeatures(degree=3, include_bias=False)

In [12]:
poly_features = poly_converter.fit_transform(X)

In [ ]:
# TRAIN AND TEST SPLIT

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [17]:
# Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [20]:
scaler.fit(X_train)

StandardScaler()

In [23]:
X_train = scaler.transform(X_train)

In [24]:
X_test = scaler.transform(X_test)

In [26]:
# RidgeCV Model

In [27]:
from sklearn.linear_model import RidgeCV

In [29]:
ridge = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [38]:
ridge.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [39]:
ridge.alpha_

0.1

In [32]:
ridge_pred = ridge.predict(X_test)

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [34]:
MAE = mean_absolute_error(y_test, ridge_pred)

In [35]:
MAE

0.42737748843352086

In [36]:
RMSE = np.sqrt(mean_squared_error(y_test, ridge_pred))

In [37]:
RMSE

0.6180719926924644

In [40]:
# Training Set Performance

In [44]:
train_pred = ridge.predict(X_train)
MAE = mean_absolute_error(y_train, train_pred)

In [45]:
MAE

0.30941321056516297

In [46]:
ridge.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [47]:
# LassoCV Model

In [48]:
from sklearn.linear_model import LassoCV

In [53]:
lasso = LassoCV(eps=0.001, n_alphas=100,cv=5, max_iter=10000000)

In [54]:
lasso.fit(X_train, y_train)

LassoCV(cv=5, max_iter=10000000)

In [56]:
lasso.alpha_

0.004943070909225827

In [57]:
lasso_pred = lasso.predict(X_test)

In [58]:
MAE = mean_absolute_error(y_test, lasso_pred)

In [59]:
MAE

0.43350346185900673

In [60]:
RMSE = np.sqrt(mean_absolute_error(y_test, lasso_pred))

In [61]:
RMSE

0.6584097978151652

In [62]:
# Training Set Performance

In [64]:
train_pred = lasso.predict(X_train)
MAE = mean_absolute_error(y_train, train_pred)

In [65]:
MAE

0.3307056225674498

In [67]:
lasso.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [68]:
# Elastic Net

In [69]:
from sklearn.linear_model import ElasticNetCV

In [70]:
elastic = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [71]:
elastic.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [72]:
elastic_pred = elastic.predict(X_test)

In [73]:
elastic.l1_ratio_

1.0

In [75]:
MAE = mean_absolute_error(y_test, elastic_pred)

In [76]:
MAE

0.5663262117569448

In [77]:
RMSE = np.sqrt(mean_absolute_error(y_test, elastic_pred))

In [78]:
RMSE

0.7525464847814684

In [79]:
# Training Set Performance

In [80]:
train_pred = elastic.predict(X_train)

In [81]:
MAE = mean_absolute_error(y_train, train_pred)

In [82]:
MAE

0.4307582990472369

In [83]:
elastic.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])